//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhabirovaMasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public int AccessID { get; set; }
        public int AccesEmployee { get; set; }
        public int AccessWorkSpace { get; set; }
        public System.DateTime AccessDateTime { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual WorkSpace WorkSpace { get; set; }
    }
}
