//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhabirovaMasterPol
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Security.Cryptography.X509Certificates;

    public partial class KhabirovaMasterPolEntities : DbContext
    {
        private static KhabirovaMasterPolEntities _context;
        public static KhabirovaMasterPolEntities GetContext()
        {
            if (_context == null)
                _context = new KhabirovaMasterPolEntities();
            return _context;
        }
        public KhabirovaMasterPolEntities()
            : base("name=KhabirovaMasterPolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access> Access { get; set; }
        public virtual DbSet<CostHistory> CostHistory { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<JobTitle> JobTitle { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialSupply> MaterialSupply { get; set; }
        public virtual DbSet<Materialtype> Materialtype { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<PartnersType> PartnersType { get; set; }
        public virtual DbSet<PointSale> PointSale { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<StockMaterial> StockMaterial { get; set; }
        public virtual DbSet<stockProduct> stockProduct { get; set; }
        public virtual DbSet<UsedMaterial> UsedMaterial { get; set; }
        public virtual DbSet<WorkSpace> WorkSpace { get; set; }
    }
}
