//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhabirovaMasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialSupply
    {
        public int MaterialSupplyID { get; set; }
        public int MaterialSupply1 { get; set; }
        public System.DateTime MaterialSupplyDate { get; set; }
        public int MaterialSupplyProvider { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
