//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhabirovaMasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CostHistory = new HashSet<CostHistory>();
            this.Request = new HashSet<Request>();
            this.stockProduct = new HashSet<stockProduct>();
            this.UsedMaterial = new HashSet<UsedMaterial>();
        }
    
        public int ProductID { get; set; }
        public int ProductType { get; set; }
        public string ProductName { get; set; }
        public string ProductArticle { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage { get; set; }
        public Nullable<int> ProductLenghtPackageCM { get; set; }
        public Nullable<int> ProductWidthPackageCM { get; set; }
        public Nullable<int> ProductHeightPackageCM { get; set; }
        public Nullable<int> ProductNetWeight { get; set; }
        public Nullable<int> ProductGrossWeight { get; set; }
        public string ProductCertificate { get; set; }
        public string ProductStandardNumber { get; set; }
        public Nullable<System.DateTime> ProductTime { get; set; }
        public Nullable<decimal> ProductCostPrice { get; set; }
        public Nullable<int> ProductWorkspaceNumber { get; set; }
        public Nullable<int> ProductNumberOfPeople { get; set; }
        public Nullable<int> ProductMaterial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostHistory> CostHistory { get; set; }
        public virtual ProductType ProductType1 { get; set; }
        public virtual WorkSpace WorkSpace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stockProduct> stockProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsedMaterial> UsedMaterial { get; set; }
    }
}
