//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhabirovaMasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.MaterialSupply = new HashSet<MaterialSupply>();
            this.StockMaterial = new HashSet<StockMaterial>();
        }
    
        public int ProviderID { get; set; }
        public int ProviderType { get; set; }
        public string ProviderName { get; set; }
        public string ProviderAdress { get; set; }
        public string ProviderINN { get; set; }
        public string ProviderDirectorName { get; set; }
        public string ProviderPhone { get; set; }
        public string ProviderEmail { get; set; }
        public string ProviderLogo { get; set; }
        public decimal ProviderRaiting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSupply> MaterialSupply { get; set; }
        public virtual PartnersType PartnersType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMaterial> StockMaterial { get; set; }
    }
}
