//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhabirovaMasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public int RequestProduct { get; set; }
        public int RequestPartners { get; set; }
        public int RequestQuantity { get; set; }
        public System.DateTime RequestDateCompletion { get; set; }
        public Nullable<decimal> RequestProductCostInUnit { get; set; }
        public Nullable<decimal> RequestPrepayment { get; set; }
        public string RequestObtaining { get; set; }
        public Nullable<int> RequestEmployee { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual Product Product { get; set; }
    }
}
