//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhabirovaMasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockProduct
    {
        public int StockProductID { get; set; }
        public string StockProductAdmissionOrOutlet { get; set; }
        public int StockProductQuantity { get; set; }
        public int StockProduct1 { get; set; }
        public System.DateTime StockProductDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
