//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhabirovaMasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMaterial
    {
        public int StockMaterialID { get; set; }
        public string StockMaterialAdmissionOrOutlet { get; set; }
        public int StockMaterialQuantity { get; set; }
        public int StockMaterial1 { get; set; }
        public int StockMaterialProvider { get; set; }
        public System.DateTime StockMaterialDate { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
